// Generated by scripts/generate_harness_types.py; do not edit.

export interface Workspace {
  files: Record<string, string>;
  graph: Graph;
  diagnostics: Array<Diagnostic>;
  compatibility: Record<string, unknown>;
  revision: string;
  active_revision?: string | null;
  draft_id?: string | null;
  status: string;
  permissions: Permissions;
  capability: string;
  capabilities: Array<string>;
  author?: string | null;
}

export interface Diagnostic {
  path: string;
  message: string;
  severity?: "error" | "warning";
}

export interface Graph {
  nodes?: Array<GraphNode>;
  edges?: Array<GraphEdge>;
}

export interface GraphEdge {
  source: string;
  target: string;
  kind: string;
}

export interface GraphNode {
  id: string;
  kind: string;
  label: string;
  parent?: string | null;
  ref?: string | null;
  source?: string | null;
  enabled?: boolean;
  reason?: string | null;
  editable?: boolean;
  details?: Record<string, unknown>;
}

export interface Permissions {
  edit?: boolean;
  review?: boolean;
}
