import React, { useEffect, useState } from 'react';
import { EyeOff, Play, RefreshCw, ShieldAlert } from 'lucide-react';
import { fetchPolicy } from '../services/api';

export const Policy: React.FC = () => {
  const [policy, setPolicy] = useState<any>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [sampleLog, setSampleLog] = useState('Paste a log line here to test local redaction.'); const [redacted, setRedacted] = useState('');
  const load = async () => { setLoading(true); setError(null); try { setPolicy(await fetchPolicy()); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load policy'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const redact = (text: string) => text.replace(/Bearer\s+[A-Za-z0-9._~+/-]+=*/gi, 'Bearer [REDACTED]').replace(/(password|passwd|secret|token|api[_-]?key)(["']?\s*[:=]\s*)(?:"[^"]*"|'[^']*'|[^\s,;}]+)/gi, '$1$2[REDACTED]').replace(/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/gi, '[EMAIL]').replace(/\b\d{3}-\d{2}-\d{4}\b/g, '[SSN]');
  const rules = policy?.skills && typeof policy.skills === 'object' ? Object.entries(policy.skills) : [];
  return <div className="view-container"><section className="hero-banner"><div className="hero-main"><h1 className="hero-title">Policy, <span>Guardrails & Redaction</span></h1><p className="hero-lede">Effective declarative policy loaded from the authenticated server scope.</p><div className="hero-meta-strip"><span className="hero-stat-chip"><span className="dot pulse" /> <b>Skill rules:</b> {loading ? 'Loading…' : rules.length}</span><span className="hero-stat-chip"><b>Source:</b> platform policy</span></div></div><div className="hero-actions"><button type="button" className="btn btn-outline" onClick={() => void load()} disabled={loading}><RefreshCw size={13} /> Refresh</button></div></section>
    {error && <div className="notice-banner red" role="alert">{error} <button className="btn btn-outline" onClick={() => void load()}>Retry</button></div>}
    <div className="card" style={{ padding: 20, marginBottom: 20 }}><h3 style={{ fontSize: 13, margin: '0 0 12px', textTransform: 'uppercase', color: 'var(--muted)', display: 'flex', gap: 6, alignItems: 'center' }}><EyeOff size={15} style={{ color: 'var(--acc)' }} /> Local redaction sandbox</h3><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}><textarea value={sampleLog} onChange={e => setSampleLog(e.target.value)} rows={4} style={{ width: '100%', padding: 10, background: 'var(--bg)', color: 'var(--text)', border: '1px solid var(--line)', borderRadius: 6 }} /><div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}><button type="button" className="btn btn-primary" onClick={() => setRedacted(redact(sampleLog))}><Play size={13} /> Run redaction</button><pre style={{ margin: 0, padding: 10, minHeight: 62, whiteSpace: 'pre-wrap', color: '#10b981', background: 'rgba(16,185,129,.03)', border: '1px solid rgba(16,185,129,.3)', borderRadius: 6 }}>{redacted || redact(sampleLog)}</pre></div></div></div>
    <div className="card" style={{ padding: 20 }}><h3 style={{ fontSize: 13, margin: '0 0 14px', textTransform: 'uppercase', color: 'var(--muted)', display: 'flex', gap: 6, alignItems: 'center' }}><ShieldAlert size={15} style={{ color: 'var(--acc)' }} /> Effective skill guardrails</h3>{loading ? <p style={{ color: 'var(--muted)' }}>Loading policy…</p> : rules.length === 0 ? <p style={{ color: 'var(--muted)' }}>No skill rules are configured.</p> : <div style={{ display: 'grid', gap: 10 }}>{rules.map(([name, raw]: [string, any]) => <div key={name} style={{ padding: 12, border: '1px solid var(--line)', borderRadius: 6 }}><b>{name}</b><div style={{ marginTop: 6, fontSize: 12, color: 'var(--muted)' }}>Actions: {(raw.actions || []).join(', ') || 'none'} · {raw.immutable ? 'Immutable' : raw.project_override ? 'Project override allowed' : 'Platform controlled'}</div></div>)}</div>}</div>
  </div>;
};
