import { ToolDefinition, ScopeLevel, ConnectorCategory, IntegrationKind } from '../types/api';

export interface ConnectorTemplateItem {
  type: string;
  name: string;
  system_name: string;
  category: ConnectorCategory;
  description: string;
  integration_kind: IntegrationKind;
  protocol: string;
  auth_method: string;
  default_endpoint: string;
  default_ui_base_url?: string;
  default_secret: string;
  default_service_user?: string;
  default_scope: ScopeLevel;
  can_override: boolean;
  default_timeout_seconds: number;
  default_retry_attempts: number;
  default_retry_backoff: number;
  default_rate_limit: string;
  default_config: Record<string, any>;
  default_mcp?: ToolDefinition['mcp_config'];
  default_a2a?: ToolDefinition['a2a_config'];
}

export const CONNECTOR_TEMPLATES: ConnectorTemplateItem[] = [
  {
    type: 'jira',
    name: 'Jira Cloud Incident Triage',
    system_name: 'jira',
    category: 'Ticketing',
    description: 'Read-only ticket ingestion, JQL polling, custom field mapping, and RCA extraction.',
    integration_kind: 'native',
    protocol: 'HTTPS',
    auth_method: 'Bearer Token',
    default_endpoint: 'https://atlassian.net/rest/api/3',
    default_ui_base_url: 'https://atlassian.net',
    default_secret: 'JIRA_API_TOKEN',
    default_service_user: 'triage-bot@organization.com',
    default_scope: 'platform_default',
    can_override: true,
    default_timeout_seconds: 30,
    default_retry_attempts: 3,
    default_retry_backoff: 5,
    default_rate_limit: '100 req/min',
    default_config: {
      project_key: 'SAG',
      polling_cron: '*/15 * * * *',
      polling_frequency: 'Every 15 minutes',
      reporting_cron: '0 17 * * 5',
      reporting_schedule: 'Every Friday at 5:00 PM Central Time',
      timezone: 'America/Chicago',
      process_attachments: true,
      team_scope: {
        core_team_values: ['Customer Info domain | CID | CHUB R2D2 Alpha', 'Quality Engineering SQaR'],
        amdocs_team_values: ['AMDOCS_BILLING_TRIAGE']
      },
      customfields: {
        fix_team: 'customfield_10290',
        environment: 'customfield_10291',
        fix_application: 'customfield_10292',
        fix_type_subtype: 'customfield_10298',
        severity: 'customfield_10285',
        fix_agent: 'customfield_10277',
        reporting_team: 'customfield_10365',
        assigned_team: 'customfield_10366',
        affected_application: 'customfield_10353',
        rca: 'customfield_10320',
        estimated_build_date: 'customfield_10321',
        acceptance_criteria: 'customfield_10313'
      }
    }
  },
  {
    type: 'splunk',
    name: 'Splunk Infrastructure & Log Mining',
    system_name: 'splunk',
    category: 'Observability',
    description: 'Time-bounded log querying, saved searches, event correlation, and metric anomaly extraction.',
    integration_kind: 'native',
    protocol: 'HTTPS',
    auth_method: 'Bearer Token',
    default_endpoint: 'https://splunk-api.prod.internal:8089',
    default_ui_base_url: 'https://splunk-ui.prod.internal:8000',
    default_secret: 'SPLUNK_HEC_TOKEN',
    default_service_user: 'splunk-api-svc@internal',
    default_scope: 'platform_default',
    can_override: true,
    default_timeout_seconds: 30,
    default_retry_attempts: 3,
    default_retry_backoff: 5,
    default_rate_limit: '120 req/min',
    default_config: {
      allowed_indexes: ['adms', 'billing', 'system', 'metrics', 'security_audit', 'gateway_logs'],
      search_app_url: 'https://splunk-ui.prod.internal:8000/en-US/app/search/search',
      wild_card_allowed: true,
      max_results: 100,
      max_window_seconds: 86400,
      data_sources: { metrics: true, events: true, logs: true },
      access_pattern: {
        mode: 'on-demand',
        detect_related_incidents: true,
        monitor_environments: ['QLAB01', 'QLAB02', 'QLAB03', 'PLAB01']
      }
    }
  },
  {
    type: 'signalfx',
    name: 'SignalFx APM & Distributed Tracing',
    system_name: 'signalfx',
    category: 'Observability',
    description: 'Distributed trace waterfall analysis, span error auto-detection, and service graphs.',
    integration_kind: 'native',
    protocol: 'HTTPS',
    auth_method: 'Bearer Token (X-SF-Token)',
    default_endpoint: 'https://signalfx-api.prod.internal/v2',
    default_ui_base_url: 'https://app.signalfx.com',
    default_secret: 'SIGNALFX_API_TOKEN',
    default_service_user: 'signalfx-telemetry@internal',
    default_scope: 'platform_default',
    can_override: true,
    default_timeout_seconds: 30,
    default_retry_attempts: 3,
    default_retry_backoff: 5,
    default_rate_limit: '150 req/min',
    default_config: {
      monitored_namespaces: ['npe-qlab01', 'npe-qlab02', 'npe-qlab03', 'npe-qlab04', 'plab01'],
      data_sources: { metrics: true, events: true, traces: true, logs: true },
      trace_correlation: {
        error_pattern: 'tls_certificate_validation_failure',
        signature: 'javax.net.ssl.SSLHandshakeException',
        trace_format: '32-char hex'
      }
    }
  },
  {
    type: 'confluence',
    name: 'Confluence Knowledge & Architecture',
    system_name: 'confluence',
    category: 'Knowledge & RAG',
    description: 'Knowledge base refresh, runbook ingestion, and architecture context mapping.',
    integration_kind: 'native',
    protocol: 'HTTPS',
    auth_method: 'Bearer Token',
    default_endpoint: 'https://atlassian.net/wiki/rest/api',
    default_ui_base_url: 'https://atlassian.net/wiki',
    default_secret: 'CONFLUENCE_API_TOKEN',
    default_service_user: 'triage-bot@organization.com',
    default_scope: 'platform_default',
    can_override: true,
    default_timeout_seconds: 30,
    default_retry_attempts: 3,
    default_retry_backoff: 5,
    default_rate_limit: '60 req/min',
    default_config: {
      spaces: ['TBD1', 'ENG', 'ARCH', 'SRE', 'RUNBOOKS'],
      refresh_schedule: 'Daily at 9:00 PM CT',
      cron: '0 21 * * *',
      timezone: 'America/Chicago'
    }
  },
  {
    type: 'qtest',
    name: 'qTest Test Case & Verification',
    system_name: 'qtest',
    category: 'Quality Assurance',
    description: 'Test case execution results, acceptance criteria link discovery, and failure tracking.',
    integration_kind: 'native',
    protocol: 'HTTPS',
    auth_method: 'Bearer Token',
    default_endpoint: 'https://qtest.corp.internal/api/v3',
    default_ui_base_url: 'https://qtest.corp.internal',
    default_secret: 'QTEST_API_TOKEN',
    default_service_user: 'qtest-svc@organization.com',
    default_scope: 'project_override',
    can_override: true,
    default_timeout_seconds: 30,
    default_retry_attempts: 3,
    default_retry_backoff: 5,
    default_rate_limit: '80 req/min',
    default_config: {
      project_id: 'PRISM-SAG-01',
      api_version: 'v3',
      monitored_environments: ['QLAB01', 'QLAB02', 'QLAB03', 'QLAB06', 'PLAB01'],
      jira_link_discovery: true,
      data_sources: { test_cases: true, test_runs: true, test_results: true, test_metrics: true }
    }
  },
  {
    type: 'gitlab',
    name: 'GitLab Source & CI/CD Pipelines',
    system_name: 'gitlab',
    category: 'Source & CI/CD',
    description: 'Commit log discovery, deployment timeline inspection, and pipeline error logs.',
    integration_kind: 'native',
    protocol: 'HTTPS',
    auth_method: 'Personal Access Token (PRIVATE-TOKEN)',
    default_endpoint: 'https://gitlab.corp.internal/api/v4',
    default_ui_base_url: 'https://gitlab.corp.internal',
    default_secret: 'GITLAB_PAT_TOKEN',
    default_service_user: 'gitlab-ci-bot@internal',
    default_scope: 'project_override',
    can_override: true,
    default_timeout_seconds: 30,
    default_retry_attempts: 3,
    default_retry_backoff: 5,
    default_rate_limit: '100 req/min',
    default_config: {
      projects: ['samson_core', 'customer_hub', 'consumer_rabbitmq'],
      default_branch: 'main',
      track_deployments: true,
      track_pipeline_logs: true,
      commit_lookback: 'P7D',
      deployments_lookback: 'P3D'
    }
  },
  {
    type: 'oracle',
    name: 'Oracle Samson Database Analytics',
    system_name: 'samson',
    category: 'Databases',
    description: 'Direct read-only SQL querying, schema table discovery, data freshness probe.',
    integration_kind: 'native',
    protocol: 'Oracle Net (TNS/OCI)',
    auth_method: 'Database Credentials (User/Password Secret)',
    default_endpoint: 'oracle-scan.corp.internal:1521/SAMSON_SRV',
    default_secret: 'ORACLE_SAMSON_SECRET',
    default_service_user: 'SAMSON_RO',
    default_scope: 'project_only',
    can_override: true,
    default_timeout_seconds: 30,
    default_retry_attempts: 2,
    default_retry_backoff: 5,
    default_rate_limit: '40 queries/min',
    default_config: {
      host: 'oracle-scan.corp.internal',
      port: 1521,
      sid: 'SAMSON01',
      service_name: 'samson.unix.internal',
      username: 'SAMSON_RO',
      schema: 'SAMSON_APP',
      default_row_limit: 500,
      read_only_enforced: true,
      allowed_statement_types: ['SELECT'],
      connection_pool: { min: 2, max: 10 }
    }
  },
  {
    type: 'kafka',
    name: 'Kafka Message Streaming & Lag Telemetry',
    system_name: 'kafka',
    category: 'Message Streaming',
    description: 'Topic partition offset inspection, consumer lag tracking, and dead-letter queue parsing.',
    integration_kind: 'native',
    protocol: 'Kafka (SASL_SSL)',
    auth_method: 'SASL/PLAIN / Client Certificate',
    default_endpoint: 'kafka-cluster.corp.internal:9092',
    default_secret: 'KAFKA_CLIENT_SECRET',
    default_service_user: 'kafka-rca-consumer',
    default_scope: 'platform_default',
    can_override: true,
    default_timeout_seconds: 15,
    default_retry_attempts: 3,
    default_retry_backoff: 5,
    default_rate_limit: '200 req/min',
    default_config: {
      bootstrap_servers: 'kafka-cluster.corp.internal:9092',
      consumer_group: 'rca-investigator-group',
      monitored_topics: ['orders.v1', 'payments.events', 'customer.cdc', 'audit.log'],
      max_records: 500,
      security_protocol: 'SSL'
    }
  },
  {
    type: 'tuxedo',
    name: 'Tuxedo Transaction Processing Monitor',
    system_name: 'Tuxedo',
    category: 'Host & Runtime Health',
    description: 'Core transaction buffer queries, service call timing, and ATMI error analysis.',
    integration_kind: 'native',
    protocol: 'WSL / TCP',
    auth_method: 'TPINIT Token',
    default_endpoint: '//tuxedo-wsl.corp.internal:8001',
    default_secret: 'TUXEDO_APP_PASSWORD',
    default_service_user: 'TUX_CLIENT_USER',
    default_scope: 'project_override',
    can_override: true,
    default_timeout_seconds: 15,
    default_retry_attempts: 2,
    default_retry_backoff: 5,
    default_rate_limit: '50 req/min',
    default_config: {
      domain_id: 'TUXDOM01',
      monitored_services: ['TOUPPER', 'ACCT_QUERY', 'CUST_SEARCH', 'BILL_INQ'],
      call_timeout_seconds: 15
    }
  },
  {
    type: 'unix',
    name: 'Unix Server Host & Syslog Mining',
    system_name: 'unix',
    category: 'Host & Runtime Health',
    description: 'Read-only server status probing, node exporter metrics, and syslog grep investigation.',
    integration_kind: 'native',
    protocol: 'SSH / Node Exporter',
    auth_method: 'SSH Key Reference',
    default_endpoint: 'ssh://app-node-01.corp.internal:22',
    default_secret: 'UNIX_SSH_KEY',
    default_service_user: 'svc-triage-ro',
    default_scope: 'project_override',
    can_override: true,
    default_timeout_seconds: 30,
    default_retry_attempts: 1,
    default_retry_backoff: 5,
    default_rate_limit: '30 req/min',
    default_config: {
      allowed_hosts: ['app-node-01.corp.internal', 'app-node-02.corp.internal', 'batch-srv-01.corp.internal'],
      read_only_enforced: true,
      prefer_templated_operations: true
    }
  },
  {
    type: 'kubernetes',
    name: 'Kubernetes Cluster & Pod Telemetry',
    system_name: 'kubernetes',
    category: 'Container Orchestration',
    description: 'Application-level pod status, CrashLoopBackOff detection, deployment rollouts, and node quotas.',
    integration_kind: 'native',
    protocol: 'HTTPS (v1)',
    auth_method: 'Kubeconfig / Service Account Token',
    default_endpoint: 'https://k8s-cluster.corp.internal:6443',
    default_ui_base_url: 'https://console.cloud.google.com/kubernetes',
    default_secret: 'K8S_SERVICE_ACCOUNT_TOKEN',
    default_service_user: 'system:serviceaccount:rca:rca-investigator',
    default_scope: 'platform_default',
    can_override: false,
    default_timeout_seconds: 20,
    default_retry_attempts: 3,
    default_retry_backoff: 5,
    default_rate_limit: '150 req/min',
    default_config: {
      cluster_name: 'npe-k8s-us-central1',
      monitored_namespaces: ['npe-qlab01', 'npe-qlab02', 'npe-qlab03', 'plab01'],
      operations: ['get_pod_status', 'get_pod_events', 'check_deployment', 'check_node_status', 'check_resource_quota'],
      events_lookback: 'P1D'
    }
  },
  {
    type: 'mcp_generic',
    name: 'Model Context Protocol (MCP) Server',
    system_name: 'custom_mcp',
    category: 'Observability',
    description: 'Standardized Model Context Protocol server exposing tool schemas over SSE or Stdio.',
    integration_kind: 'mcp',
    protocol: 'MCP (SSE)',
    auth_method: 'MCP Bearer Token',
    default_endpoint: 'mcp://service-mcp.internal:9090',
    default_secret: 'MCP_SERVICE_TOKEN',
    default_service_user: 'mcp-client',
    default_scope: 'platform_default',
    can_override: true,
    default_timeout_seconds: 15,
    default_retry_attempts: 3,
    default_retry_backoff: 5,
    default_rate_limit: '300 req/min',
    default_config: {},
    default_mcp: {
      transport: 'sse',
      tools_exposed: ['query_status', 'search_data', 'stream_events']
    }
  },
  {
    type: 'a2a_generic',
    name: 'Agent-to-Agent (A2A) Delegation Bridge',
    system_name: 'a2a_agent_bridge',
    category: 'Host & Runtime Health',
    description: 'Google ADK native AgentTool delegation or A2A REST protocol for multi-agent investigation.',
    integration_kind: 'a2a',
    protocol: 'ADK AgentTool',
    auth_method: 'Mutual TLS & RS256 JWT',
    default_endpoint: 'http://agent-service.internal:8000/a2a/v1',
    default_secret: 'AGENT_DELEGATION_SECRET',
    default_service_user: 'rca-orchestrator',
    default_scope: 'project_override',
    can_override: true,
    default_timeout_seconds: 45,
    default_retry_attempts: 2,
    default_retry_backoff: 5,
    default_rate_limit: '100 req/min',
    default_config: {},
    default_a2a: {
      target_agent_id: 'specialist-investigator-agent',
      target_capability: 'specialized_investigation',
      delegation_protocol: 'adk_agent_tool',
      dual_custody_approved: true,
      content_hash: 'sha256:d189b882ac0012'
    }
  }
];

export const DEFAULT_SYSTEM_TOOLS: ToolDefinition[] = [
  {
    id: 'tool-jira-cloud',
    name: 'Jira Cloud Incident Triage',
    system_name: 'jira',
    category: 'Ticketing',
    description: 'Read-only ticket ingestion, JQL polling, custom field mapping, and RCA extraction.',
    status: 'connected',
    enabled: true,
    type: 'connector',
    integration_kind: 'native',
    scope_level: 'platform_default',
    project_can_override: true,
    inherit_platform_defaults: true,
    rate_limit: '100 req/min',
    last_ping: '200 OK • Schema verified',
    latency_ms: 124,
    calls_today: 1420,
    error_rate: 0.02,
    endpoint: 'https://atlassian.net/rest/api/3',
    ui_base_url: 'https://atlassian.net',
    auth_method: 'Bearer Token',
    secret_reference: 'JIRA_API_TOKEN',
    service_user: 'triage-bot@organization.com',
    protocol: 'HTTPS',
    timeout_seconds: 30,
    retry_attempts: 3,
    retry_backoff_seconds: 5,
    max_response_bytes: 1048576,
    verify_ssl: true,
    token_header_format: 'Authorization: Bearer {JIRA_API_TOKEN}',
    project_key: 'SAG',
    custom_config: {
      project_key: 'SAG',
      polling_cron: '*/15 * * * *',
      polling_frequency: 'Every 15 minutes',
      reporting_cron: '0 17 * * 5',
      reporting_schedule: 'Every Friday at 5:00 PM Central Time',
      timezone: 'America/Chicago',
      process_attachments: true,
      team_scope: {
        core_team_values: ['Customer Info domain | CID | CHUB R2D2 Alpha', 'Quality Engineering SQaR'],
        amdocs_team_values: ['AMDOCS_BILLING_TRIAGE']
      },
      customfields: {
        fix_team: 'customfield_10290',
        environment: 'customfield_10291',
        fix_application: 'customfield_10292',
        fix_type_subtype: 'customfield_10298',
        severity: 'customfield_10285',
        fix_agent: 'customfield_10277',
        reporting_team: 'customfield_10365',
        assigned_team: 'customfield_10366',
        affected_application: 'customfield_10353',
        rca: 'customfield_10320',
        estimated_build_date: 'customfield_10321',
        acceptance_criteria: 'customfield_10313'
      }
    }
  },
  {
    id: 'tool-splunk-enterprise',
    name: 'Splunk Infrastructure & Log Mining',
    system_name: 'splunk',
    category: 'Observability',
    description: 'Time-bounded log querying, saved searches, event correlation, and metric anomaly extraction.',
    status: 'connected',
    enabled: true,
    type: 'connector',
    integration_kind: 'native',
    scope_level: 'platform_default',
    project_can_override: true,
    inherit_platform_defaults: true,
    rate_limit: '120 req/min',
    last_ping: '200 OK • Index verified',
    latency_ms: 185,
    calls_today: 3890,
    error_rate: 0.01,
    endpoint: 'https://splunk-api.prod.internal:8089',
    ui_base_url: 'https://splunk-ui.prod.internal:8000',
    auth_method: 'Bearer Token',
    secret_reference: 'SPLUNK_HEC_TOKEN',
    service_user: 'splunk-api-svc@internal',
    protocol: 'HTTPS',
    timeout_seconds: 30,
    retry_attempts: 3,
    retry_backoff_seconds: 5,
    max_response_bytes: 4194304,
    verify_ssl: true,
    token_header_format: 'Authorization: Bearer {SPLUNK_HEC_TOKEN}',
    custom_config: {
      allowed_indexes: ['adms', 'billing', 'system', 'metrics', 'security_audit', 'gateway_logs'],
      search_app_url: 'https://splunk-ui.prod.internal:8000/en-US/app/search/search',
      wild_card_allowed: true,
      max_results: 100,
      max_window_seconds: 86400,
      data_sources: { metrics: true, events: true, logs: true },
      access_pattern: {
        mode: 'on-demand',
        detect_related_incidents: true,
        monitor_environments: ['QLAB01', 'QLAB02', 'QLAB03', 'PLAB01']
      }
    }
  },
  {
    id: 'tool-signalfx-apm',
    name: 'SignalFx APM & Distributed Tracing',
    system_name: 'signalfx',
    category: 'Observability',
    description: 'Distributed trace waterfall analysis, span error auto-detection, and service graphs.',
    status: 'connected',
    enabled: true,
    type: 'connector',
    integration_kind: 'native',
    scope_level: 'platform_default',
    project_can_override: true,
    inherit_platform_defaults: true,
    rate_limit: '150 req/min',
    last_ping: '200 OK • Ingest active',
    latency_ms: 98,
    calls_today: 5120,
    error_rate: 0.00,
    endpoint: 'https://signalfx-api.prod.internal/v2',
    ui_base_url: 'https://app.signalfx.com',
    auth_method: 'Bearer Token (X-SF-Token)',
    secret_reference: 'SIGNALFX_API_TOKEN',
    service_user: 'signalfx-telemetry@internal',
    protocol: 'HTTPS',
    timeout_seconds: 30,
    retry_attempts: 3,
    retry_backoff_seconds: 5,
    max_response_bytes: 2097152,
    verify_ssl: true,
    token_header_format: 'X-SF-Token: {SIGNALFX_API_TOKEN}',
    custom_config: {
      monitored_namespaces: ['npe-qlab01', 'npe-qlab02', 'npe-qlab03', 'npe-qlab04', 'plab01'],
      data_sources: { metrics: true, events: true, traces: true, logs: true },
      trace_correlation: {
        error_pattern: 'tls_certificate_validation_failure',
        signature: 'javax.net.ssl.SSLHandshakeException',
        trace_format: '32-char hex'
      }
    }
  },
  {
    id: 'tool-confluence-kb',
    name: 'Confluence Knowledge & Architecture',
    system_name: 'confluence',
    category: 'Knowledge & RAG',
    description: 'Knowledge base refresh, runbook ingestion, and architecture context mapping.',
    status: 'connected',
    enabled: true,
    type: 'connector',
    integration_kind: 'native',
    scope_level: 'platform_default',
    project_can_override: true,
    inherit_platform_defaults: true,
    rate_limit: '60 req/min',
    last_ping: '200 OK • Spaces synced',
    latency_ms: 160,
    calls_today: 420,
    error_rate: 0.00,
    endpoint: 'https://atlassian.net/wiki/rest/api',
    ui_base_url: 'https://atlassian.net/wiki',
    auth_method: 'Bearer Token',
    secret_reference: 'CONFLUENCE_API_TOKEN',
    service_user: 'triage-bot@organization.com',
    protocol: 'HTTPS',
    timeout_seconds: 30,
    retry_attempts: 3,
    retry_backoff_seconds: 5,
    custom_config: {
      spaces: ['TBD1', 'ENG', 'ARCH', 'SRE', 'RUNBOOKS'],
      refresh_schedule: 'Daily at 9:00 PM CT',
      cron: '0 21 * * *',
      timezone: 'America/Chicago'
    }
  },
  {
    id: 'tool-qtest-qa',
    name: 'qTest Test Case & Verification',
    system_name: 'qtest',
    category: 'Quality Assurance',
    description: 'Test case execution results, acceptance criteria link discovery, and failure tracking.',
    status: 'connected',
    enabled: true,
    type: 'connector',
    integration_kind: 'native',
    scope_level: 'project_override',
    project_can_override: true,
    inherit_platform_defaults: true,
    rate_limit: '80 req/min',
    last_ping: '200 OK • 5 runs indexed',
    latency_ms: 210,
    calls_today: 310,
    error_rate: 0.03,
    endpoint: 'https://qtest.corp.internal/api/v3',
    ui_base_url: 'https://qtest.corp.internal',
    auth_method: 'Bearer Token',
    secret_reference: 'QTEST_API_TOKEN',
    service_user: 'qtest-svc@organization.com',
    protocol: 'HTTPS',
    timeout_seconds: 30,
    retry_attempts: 3,
    retry_backoff_seconds: 5,
    custom_config: {
      project_id: 'PRISM-SAG-01',
      api_version: 'v3',
      monitored_environments: ['QLAB01', 'QLAB02', 'QLAB03', 'QLAB06', 'PLAB01'],
      jira_link_discovery: true,
      data_sources: { test_cases: true, test_runs: true, test_results: true, test_metrics: true }
    }
  },
  {
    id: 'tool-gitlab-ci',
    name: 'GitLab Source & CI/CD Pipelines',
    system_name: 'gitlab',
    category: 'Source & CI/CD',
    description: 'Commit log discovery, deployment timeline inspection, and pipeline error logs.',
    status: 'connected',
    enabled: true,
    type: 'connector',
    integration_kind: 'native',
    scope_level: 'project_override',
    project_can_override: true,
    inherit_platform_defaults: true,
    rate_limit: '100 req/min',
    last_ping: '200 OK • Webhooks active',
    latency_ms: 115,
    calls_today: 840,
    error_rate: 0.01,
    endpoint: 'https://gitlab.corp.internal/api/v4',
    ui_base_url: 'https://gitlab.corp.internal',
    auth_method: 'Personal Access Token (PRIVATE-TOKEN)',
    secret_reference: 'GITLAB_PAT_TOKEN',
    service_user: 'gitlab-ci-bot@internal',
    protocol: 'HTTPS',
    timeout_seconds: 30,
    retry_attempts: 3,
    retry_backoff_seconds: 5,
    custom_config: {
      projects: ['samson_core', 'customer_hub', 'consumer_rabbitmq'],
      default_branch: 'main',
      track_deployments: true,
      track_pipeline_logs: true,
      commit_lookback: 'P7D',
      deployments_lookback: 'P3D'
    }
  },
  {
    id: 'tool-oracle-samson',
    name: 'Oracle Samson Database Analytics',
    system_name: 'samson',
    category: 'Databases',
    description: 'Direct read-only SQL querying, schema table discovery, data freshness probe.',
    status: 'connected',
    enabled: true,
    type: 'connector',
    integration_kind: 'native',
    scope_level: 'project_only',
    project_can_override: true,
    inherit_platform_defaults: false,
    rate_limit: '40 queries/min',
    last_ping: '200 OK • Read-only verified',
    latency_ms: 45,
    calls_today: 1290,
    error_rate: 0.00,
    endpoint: 'oracle-scan.corp.internal:1521/SAMSON_SRV',
    auth_method: 'Database Credentials (User/Password Secret)',
    secret_reference: 'ORACLE_SAMSON_SECRET',
    service_user: 'SAMSON_RO',
    protocol: 'Oracle Net (TNS/OCI)',
    timeout_seconds: 30,
    retry_attempts: 2,
    retry_backoff_seconds: 5,
    custom_config: {
      host: 'oracle-scan.corp.internal',
      port: 1521,
      sid: 'SAMSON01',
      service_name: 'samson.unix.internal',
      username: 'SAMSON_RO',
      schema: 'SAMSON_APP',
      default_row_limit: 500,
      read_only_enforced: true,
      allowed_statement_types: ['SELECT'],
      connection_pool: { min: 2, max: 10 }
    }
  },
  {
    id: 'tool-kafka-streaming',
    name: 'Kafka Message Streaming & Lag Telemetry',
    system_name: 'kafka',
    category: 'Message Streaming',
    description: 'Topic partition offset inspection, consumer lag tracking, and dead-letter queue parsing.',
    status: 'connected',
    enabled: true,
    type: 'connector',
    integration_kind: 'native',
    scope_level: 'platform_default',
    project_can_override: true,
    inherit_platform_defaults: true,
    rate_limit: '200 req/min',
    last_ping: '200 OK • Cluster synced',
    latency_ms: 38,
    calls_today: 6700,
    error_rate: 0.00,
    endpoint: 'kafka-cluster.corp.internal:9092',
    auth_method: 'SASL/PLAIN / Client Certificate',
    secret_reference: 'KAFKA_CLIENT_SECRET',
    service_user: 'kafka-rca-consumer',
    protocol: 'Kafka (SASL_SSL)',
    timeout_seconds: 15,
    retry_attempts: 3,
    retry_backoff_seconds: 5,
    custom_config: {
      bootstrap_servers: 'kafka-cluster.corp.internal:9092',
      consumer_group: 'rca-investigator-group',
      monitored_topics: ['orders.v1', 'payments.events', 'customer.cdc', 'audit.log'],
      max_records: 500,
      security_protocol: 'SSL'
    }
  },
  {
    id: 'tool-tuxedo-transactions',
    name: 'Tuxedo Transaction Processing Monitor',
    system_name: 'Tuxedo',
    category: 'Host & Runtime Health',
    description: 'Core transaction buffer queries, service call timing, and ATMI error analysis.',
    status: 'connected',
    enabled: true,
    type: 'connector',
    integration_kind: 'native',
    scope_level: 'project_override',
    project_can_override: true,
    inherit_platform_defaults: true,
    rate_limit: '50 req/min',
    last_ping: '200 OK • WSL connected',
    latency_ms: 65,
    calls_today: 490,
    error_rate: 0.02,
    endpoint: '//tuxedo-wsl.corp.internal:8001',
    auth_method: 'TPINIT Token',
    secret_reference: 'TUXEDO_APP_PASSWORD',
    service_user: 'TUX_CLIENT_USER',
    protocol: 'WSL / TCP',
    timeout_seconds: 15,
    retry_attempts: 2,
    retry_backoff_seconds: 5,
    custom_config: {
      domain_id: 'TUXDOM01',
      monitored_services: ['TOUPPER', 'ACCT_QUERY', 'CUST_SEARCH', 'BILL_INQ'],
      call_timeout_seconds: 15
    }
  },
  {
    id: 'tool-unix-host',
    name: 'Unix Server Host & Syslog Mining',
    system_name: 'unix',
    category: 'Host & Runtime Health',
    description: 'Read-only server status probing, node exporter metrics, and syslog grep investigation.',
    status: 'connected',
    enabled: true,
    type: 'connector',
    integration_kind: 'native',
    scope_level: 'project_override',
    project_can_override: true,
    inherit_platform_defaults: true,
    rate_limit: '30 req/min',
    last_ping: '200 OK • Host reachable',
    latency_ms: 78,
    calls_today: 230,
    error_rate: 0.00,
    endpoint: 'ssh://app-node-01.corp.internal:22',
    auth_method: 'SSH Key Reference',
    secret_reference: 'UNIX_SSH_KEY',
    service_user: 'svc-triage-ro',
    protocol: 'SSH / Node Exporter',
    timeout_seconds: 30,
    retry_attempts: 1,
    retry_backoff_seconds: 5,
    custom_config: {
      allowed_hosts: ['app-node-01.corp.internal', 'app-node-02.corp.internal', 'batch-srv-01.corp.internal'],
      read_only_enforced: true,
      prefer_templated_operations: true
    }
  },
  {
    id: 'tool-k8s-telemetry',
    name: 'Kubernetes Cluster & Pod Telemetry',
    system_name: 'kubernetes',
    category: 'Container Orchestration',
    description: 'Application-level pod status, CrashLoopBackOff detection, deployment rollouts, and node quotas.',
    status: 'connected',
    enabled: true,
    type: 'connector',
    integration_kind: 'native',
    scope_level: 'platform_default',
    project_can_override: false,
    inherit_platform_defaults: true,
    rate_limit: '150 req/min',
    last_ping: '200 OK • K8s v1.28',
    latency_ms: 55,
    calls_today: 4210,
    error_rate: 0.00,
    endpoint: 'https://k8s-cluster.corp.internal:6443',
    ui_base_url: 'https://console.cloud.google.com/kubernetes',
    auth_method: 'Kubeconfig / Service Account Token',
    secret_reference: 'K8S_SERVICE_ACCOUNT_TOKEN',
    service_user: 'system:serviceaccount:rca:rca-investigator',
    protocol: 'HTTPS (v1)',
    timeout_seconds: 20,
    retry_attempts: 3,
    retry_backoff_seconds: 5,
    custom_config: {
      cluster_name: 'npe-k8s-us-central1',
      monitored_namespaces: ['npe-qlab01', 'npe-qlab02', 'npe-qlab03', 'plab01'],
      operations: ['get_pod_status', 'get_pod_events', 'check_deployment', 'check_node_status', 'check_resource_quota'],
      events_lookback: 'P1D'
    }
  },
  {
    id: 'tool-mcp-cluster',
    name: 'Model Context Protocol (MCP) Server',
    system_name: 'custom_mcp',
    category: 'Observability',
    description: 'Standardized Model Context Protocol server exposing dynamic tool schemas over SSE or Stdio.',
    status: 'connected',
    enabled: true,
    type: 'mcp',
    integration_kind: 'mcp',
    scope_level: 'platform_default',
    project_can_override: true,
    inherit_platform_defaults: true,
    rate_limit: '300 req/min',
    last_ping: '200 OK • 3 tools bound',
    latency_ms: 22,
    calls_today: 1850,
    error_rate: 0.00,
    endpoint: 'mcp://service-mcp.internal:9090',
    auth_method: 'MCP Bearer Token',
    secret_reference: 'MCP_SERVICE_TOKEN',
    service_user: 'mcp-client',
    protocol: 'MCP (SSE)',
    timeout_seconds: 15,
    retry_attempts: 3,
    retry_backoff_seconds: 5,
    mcp_config: {
      transport: 'sse',
      tools_exposed: ['query_status', 'search_data', 'stream_events']
    }
  },
  {
    id: 'tool-a2a-bridge',
    name: 'Agent-to-Agent (A2A) Delegation Bridge',
    system_name: 'a2a_agent_bridge',
    category: 'Host & Runtime Health',
    description: 'Google ADK native AgentTool delegation or A2A REST protocol for multi-agent investigation.',
    status: 'connected',
    enabled: true,
    type: 'a2a',
    integration_kind: 'a2a',
    scope_level: 'project_override',
    project_can_override: true,
    inherit_platform_defaults: true,
    rate_limit: '100 req/min',
    last_ping: '200 OK • Dual-custody signed',
    latency_ms: 18,
    calls_today: 720,
    error_rate: 0.00,
    endpoint: 'http://agent-service.internal:8000/a2a/v1',
    auth_method: 'Mutual TLS & RS256 JWT',
    secret_reference: 'AGENT_DELEGATION_SECRET',
    service_user: 'rca-orchestrator',
    protocol: 'ADK AgentTool',
    timeout_seconds: 45,
    retry_attempts: 2,
    retry_backoff_seconds: 5,
    a2a_config: {
      target_agent_id: 'specialist-investigator-agent',
      target_capability: 'specialized_investigation',
      delegation_protocol: 'adk_agent_tool',
      dual_custody_approved: true,
      content_hash: 'sha256:d189b882ac0012'
    }
  }
];
