"""Export a schema-only reference from a disposable migrated PostgreSQL database."""

import argparse
import os
import re
from pathlib import Path
import subprocess

from sqlalchemy.engine import make_url

SCHEMAS = {
    "platform": "Shared catalogs, identity, connector configuration and reviewed knowledge; tenant/project scope is explicit.",
    "project": "Project bootstrap identity and scoped parameter overrides; cross-schema validation protects definitions.",
    "runtime": "Investigation, evidence, chat, feedback and browser-session records; foreign keys preserve ownership relationships.",
    "governance": "Review drafts, approvals and append-only audit records; hashes identify reviewed content.",
    "optimization": "Immutable benchmark registrations, evaluated revisions and project activation pointers.",
    "adk": "Native ADK sessions/events and state; retain upstream schema conventions and metadata bootstrap.",
    "mlflow": "Native MLflow tracking and prompt/evaluation metadata; managed by upstream migrations, not application models.",
}


def export_ddl(url: str) -> str:
    parsed = make_url(url)
    if parsed.get_backend_name() != "postgresql":
        raise ValueError("DDL export requires PostgreSQL")
    environment = dict(os.environ)
    if parsed.password is not None:
        environment["PGPASSWORD"] = parsed.password
    database = parsed.set(drivername="postgresql", password=None).render_as_string(hide_password=False)
    parts = [
        "-- Consolidated schema-only reference; generated by scripts.export_database_ddl.\n"
        "-- No seed data, migration ledger entries or native version rows are included.\n"
        "-- Deploy/upgrade through scripts.migrate, not this reference snapshot.\n"
        "-- The rca_app role must exist when restoring privileges for verification.\n"
        "-- All tables precede post-data constraints to preserve cross-schema dependencies.\n"
    ]
    for section in ("pre-data", "post-data"):
        for schema in SCHEMAS:
            result = subprocess.run(
                ["pg_dump", "--dbname", database, "--schema-only", "--no-owner", f"--schema={schema}", f"--section={section}"],
                env=environment, capture_output=True, text=True, check=False,
            )
            if result.returncode:
                # Do not echo connection details from subprocess errors.
                raise RuntimeError(f"pg_dump failed for {schema}/{section}")
            lines = [line for line in result.stdout.splitlines()
                     if not line.startswith(("\\restrict ", "\\unrestrict ", "-- Dumped "))]
            # Pre-data creates tables/functions; post-data adds keys, indexes and
            # triggers only after every referenced schema has been created.
            purpose = "Tables, sequences and functions" if section == "pre-data" else "Constraints, indexes, triggers and access grants"
            parts.append(f"\n-- ===== {schema}: {section} =====\n-- {SCHEMAS[schema]}\n-- {purpose}.\n" + re.sub(r"; Owner: .*", "; Owner: omitted", "\n".join(lines)).strip() + "\n")
    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("migrations/schema.sql"))
    args = parser.parse_args()
    url = os.environ.get("RCA_MIGRATION_DATABASE_URL")
    if not url:
        raise SystemExit("Set RCA_MIGRATION_DATABASE_URL to a disposable migrated database")
    args.output.write_text(export_ddl(url))


if __name__ == "__main__":
    main()
